- Gemfile
- Gemfile.lock
- app/assets/stylesheets/views/_contact-show.scss
- app/controllers/application_controller.rb
- app/controllers/contacts_controller.rb
- app/views/contacts/show.html.erb
Switch to using govuk_components for the beta banner rather than the
slimmer variant.
Upgraded slimmer to the latest version so that components were
available.
Introduced a beta-wrapper to ensure the beta bar is correctly placed on
the page at the right width with the right margins.
> Use components for beta banner

- app/assets/stylesheets/views/_contact-show.scss
- app/assets/stylesheets/views/_layout.scss
- app/views/contacts/show.html.erb
The template is changing to auto-center and provide layout to pages.
This makes these pages ready for that change.
Updated the related element to actually match the markup from the static
version. It had a couple of enhancements over the version that was here
like having the aria-labelled by actually pointing to the right
headings.
It also adds a main element to the page which is used for the layout in
static.
This is related to this pull request on static: https://github.com/alphagov/static/pull/530
> Update for new slimmer template updates

- app/views/contacts/show.html.erb
- app/views/layouts/application.html.erb
- spec/features/contact_page_spec.rb
Part of improving search result snipperts shown on external search engines.
The lack of a meta-description tag makes some search result snippets unhelpful, confusing, or misleading. Ticket: https://trello.com/c/S6VUwRWQ/273-follow-up-add-meta-description-tag-to-custom-content-types
> Add meta description tag for contacts

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
Explicitly set the slimmer template to be wrapper so that it isn't
effected by changes to the default when slimmer is updated.
> Set slimmer template to be wrapper

- app/views/contacts/show.html.erb
- app/views/layouts/application.html.erb
- spec/features/contact_page_spec.rb
Contact pages all have the same `<title>` tag: "{organisation.title} contacts". There are 133 HMRC pages that have the same title, which causes google to correct them to something unique:
(note that Google doesn't use the correct capitalisation of "GOV.UK" - that's how you can see Google has modified the title)
This commit changes the page title to the form
> "Air Passenger Duty - Contact HMRC - GOV.UK"
> Set a correct title for contact pages

- README.md
`hmrc-contacts` repo was renamed to `contacts-admin`. GH happily redirected the links, but the name was confusing.
> Update name of contacts-admin repo

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/views/_contact-show.scss
- app/views/contacts/_post_address.html.erb
When printing, each part of the address was appearing on a single line, and the first line appeared above it as a header. Anyone printing these pages and then transcribing the address would likely send things to the wrong place.
* Don’t use styled spans, use divs (empty divs will have a zero height, whereas spans with line breaks would create new lines for empty parts)
* Don’t use a heading for the title
* Bump govuk_frontend_toolkit
https://trello.com/c/jT7QTzBb/145-fix-print-styles-on-addresses-medium
> Fix postal address print styles

- Gemfile
- Gemfile.lock
- jenkins.sh
- spec/contracts/govuk_content_schemas_spec.rb
- spec/support/govuk_content_schemas.rb
Any feedback welcome!
Inspired by documentation for `govuk-content-schema-helpers` (https://github.com/alphagov/govuk-content-schema-test-helpers/blob/master/README.md).
File structure similar to implementation of contract testing for `manuals-frontend`
> Add contract tests against content schema

- jenkins-schema.sh
- This was causing upstream builds to fail because, embarrassingly, it
didn't pass because it was calling the wrong thing. The perils of copy
and paste from different projects! Thanks, Tijmen!
Related: https://github.com/alphagov/contacts-frontend/pull/38
> Fix the CI build for the content_schemas jenkins-schema.sh

- app/presenters/contact_presenter.rb
- app/views/contacts/show.html.erb
- spec/features/contact_page_spec.rb
- spec/fixtures/content_store/hmrc_ated.json
- spec/presenters/contact_presenter_spec.rb
- The use of the organisation's abbreviation (HMRC instead of HM Revenue
and Customs) was complicating our content schema unnecessarily and
forcing us to still use the organisation data from Whitehall, not the
new world content-store, as it contained the `abbreviation` field we
required. This change enables us to also change the organisations data
to fetch from the `links`, not the details.
- Visually, the changes look OK, and Mark S. has approved this approach.
Before:
After:
(This will need a staged deploy with https://github.com/alphagov/contacts-admin/pull/219, after running the rake task over there so that all contacts have organisation `content_id`s, so that nothing breaks for users. Tested on Preview, with the contacts-admin stuff already done, and it's successful.)
(Trello: …
> Use an organisation's title in breadcrumbs instead of its abbreviation

- app/assets/stylesheets/views/_contact-show.scss
This PR stops phone numbers from going *up* in font size on mobile, rather than down, as they should.
> Remove hard coded font size - fall back to inherited

- app/views/layouts/application.html.erb
For https://trello.com/c/ALk6AOEN/215-contacts-add-google-analytics-using-the-new-component
This adds tracking for `format` (dimension 2) and `organisation` (dimension 9) to the app, using the [google analytics component](https://github.com/alphagov/static/blob/master/app/views/govuk_component/analytics_meta_tags.raw.html.erb).
The following Markup is generated (truncated):
```
<meta content="authenticity_token" name="csrf-param">
<meta content="YEUU36M7scIpSbH69R/DnRmgyPJzOGVlBcN4/mwsU/Q=" name="csrf-token">
<meta name="govuk:format" content="contact">
<meta name="govuk:analytics:organisations" content="&lt;D25&gt;">
<meta name="description" content="Call or write to HMRC if you're an aircraft operator and need help with Air Passenger Duty, including registering and making payments and …
```
> Use GA component to track format and organisation

- app/views/layouts/application.html.erb
`role="breadcrumbs"` is not a thing.
https://www.w3.org/TR/wai-aria/roles#role_definitions
We previously removed from the component:
https://github.com/alphagov/static/pull/737
> Remove invalid breadcrumbs aria role

- app/assets/javascripts/webchat.js
- app/presenters/contact_presenter.rb
- app/views/contacts/_contact_details.html.erb
This enables the new webchat for the VAT enquiries page.
It also removes the opening times for webchat. This is because the current opening times of HMRC webchat are more flexible than suggested. Sometimes webchat is open earlier or later in the day, and at times may be closed while advisors handle other channels. This means the published opening times are misleading and causing confusion.
Should be merged alongside https://github.com/alphagov/static/pull/828
> Add webchat to VAT enquiries page and remove opening times

- app/assets/javascripts/webchat.js
- app/presenters/contact_presenter.rb
This pull request enables the HMRC webchat contact method on the Tax Credits contact page.
This will need to be deployed alongside a change in static to disable the original webchat implementation on this page (https://github.com/alphagov/static/pull/829).
> Enable webchat contact method on Tax Credits page

- app/assets/javascripts/webchat.js
- app/presenters/contact_presenter.rb
**Not to be merged until 7 September**
This pull request enables HMRC webchat as a contact method on the Self Assessment enquiries page.
It needs to be deployed alongside a change in static to disable the original webchat service (https://github.com/alphagov/static/pull/830).
> Enable webchat on Self Assessment enquiries page

- app/assets/javascripts/webchat.js
- app/presenters/contact_presenter.rb
**Not to be deployed until 12 September**
This enables webchat on the National Insurance Number and Self Assessment online enquiries contact pages.
It should be deployed alongside a change in static to disable the original webchat implementation on these pages (https://github.com/alphagov/static/pull/831).
> Enable webchat on NINO & SA online pages

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/contacts_controller.rb
- app/presenters/contact_presenter.rb
- config/initializers/gds_api_adapters.rb
- spec/features/contact_page_spec.rb
- Trello card:  https://trello.com/c/B5z6Dq8q/495.
- Some old behaviour has been deprecated in [gds-api-adapters](https://github.com/alphagov/gds-api-adapters) so we are updating this app to comply with this before it becomes the default. Firstly, a GdsApi::NotFound error is now raised when the server returns a 404 or 410.  Secondly, requests now return a hash instead of an OpenStruct.  We have now opted in to this new behaviour.
> Use new GDS API Adapters behaviour

- README.md
Update the README to reflect that.
PR with that change: https://github.com/alphagov/contacts-admin/pull/249
> The index page is now served by finder-frontend

- spec/features/contact_page_spec.rb
This test would sometimes fail, returning 899 rather than 900 for expiry seconds. This is caused by the `GdsApi::Response.expires_in` method with dynamically calculates this value based on when you call it. It's used in the Contacts controller to set the expiry headers. It would 899 if the request takes longer than a second to process. We stub the value to ensure it always matches the expectation.
See https://github.com/alphagov/gds-api-adapters/blob/45fdbf98398f1fab97ac26164db1621d3390aec5/lib/gds_api/response.rb#L57-L67
To replace https://github.com/alphagov/contacts-frontend/pull/63
> Fix intermittent expiry test failure

- app/assets/javascripts/webchat.js
- app/presenters/contact_presenter.rb
This should go out on the 15th of December.
Trello card: https://trello.com/c/dtueOo2D/530-click-to-chat
> Enable HMRC webchat for specialist tax trusts

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/views/contacts/show.html.erb
- app/views/layouts/application.html.erb
- spec/contracts/govuk_content_schemas_spec.rb
- spec/features/contact_page_spec.rb
- spec/spec_helper.rb
- There is no change to the appearance or text of the breadcrumbs, but
they are now rendered by the govuk_component.
[Trello card](https://trello.com/c/TekeTJ9Y/401-use-govuk-component-in-contacts-frontend)
> Render breadcrumbs using the govuk_component

- jenkins-schema.sh
As of https://github.com/alphagov/contacts-frontend/pull/67, `slimmer` now requests locale data, which is stubbed out in the tests using `stub_shared_component_locales`. This method stubs all calls to `gov.uk` domains, while the schema test runner still uses the old `alphagov.co.uk` domains. Due to this, schema tests are not passing.
> Update domains used for schema tests

- jenkins-schema.sh
- spec/spec_helper.rb
These env vars should apply across tests, not just for Jenkins schema tests.
> Move test env vars to spec helper
